//
//  QuestionareWorker.swift
//  CleanSwift
//
//  Created by Nuntapat Hirunnattee on 7/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class QuestionareWorker
{
    func doSomeWork()
    {
        //so API caller
    }
}
