//
//  QuestionareInteractor.swift
//  CleanSwift
//
//  Created by Nuntapat Hirunnattee on 7/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionareBusinessLogic
{
    func getLoanCondition(request: Questionare.Loan.Request)
}

protocol QuestionareDataStore
{
    //var name: String { get set }
}

class QuestionareInteractor: QuestionareBusinessLogic, QuestionareDataStore
{
    
    
    var presenter: QuestionarePresentationLogic?
    var worker: QuestionareWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getLoanCondition(request: Questionare.Loan.Request) {
        let career = request.career
        
        var rate = 0.0
        var period = 0
        var loan = 0
        
        switch career {
        case .governmentEmployee:
            rate = 0.5
            period = 60
            loan = 2000000
            
        case .companyEmployee:
            rate = 1.5
            period = 36
            loan = 1500000
            
        case .ownBusiness:
            rate = 2.5
            period = 24
            loan = 1000000
            
        }
        
        let response = Questionare.Loan.Response(career: career, rate: rate, period: period, loan: loan)
        presenter?.presentLoanInformation(response: response)
        
    }
}
