//
//  QuestionarePresenter.swift
//  CleanSwift
//
//  Created by Nuntapat Hirunnattee on 7/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionarePresentationLogic
{
    func presentLoanInformation(response: Questionare.Loan.Response)
}

class QuestionarePresenter: QuestionarePresentationLogic
{
    
    weak var viewController: QuestionareDisplayLogic?
    
    // MARK: Do something
    
    func presentLoanInformation(response: Questionare.Loan.Response) {
        let message = "You can maximum loan up to \(response.loan) bath interest rate is \(response.rate) maximum priod up to \(response.period) round"
        let isGovernmentEmployee = response.career == .governmentEmployee
        let isCompanyEmployee = response.career == .companyEmployee
        let isOwnBusiness = response.career == .ownBusiness
        
        let viewModel = Questionare.Loan.ViewModel(message: message, isGovernmentEmployee: isGovernmentEmployee, isCompanyEmployee: isCompanyEmployee, isOwnBusiness: isOwnBusiness)
        
        viewController?.DisplayLoanCondition(viewModel: viewModel)
    }
}
