//
//  QuestionareModels.swift
//  CleanSwift
//
//  Created by Nuntapat Hirunnattee on 7/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Questionare
{
    
    // MARK: Use cases
    
    enum Loan{
        
        struct Request{
            var career: Career
        }
        
        struct Response{
            var career: Career
            var rate: Double
            var period: Int
            var loan: Int
        }
        
        struct ViewModel{
            var message: String
            var isGovernmentEmployee: Bool
            var isCompanyEmployee: Bool
            var isOwnBusiness: Bool
        }
    }
    
}

enum Career{
    case governmentEmployee
    case companyEmployee
    case ownBusiness
}
